# Generated by Django 2.1.2 on 2018-11-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_start', '0004_auto_20181101_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', related_query_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
